version: '3.7'

services:
  php:
    container_name: lemp_php
    build: Dockerfile/php/ 
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  nginx:
    container_name: lemp_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
      - ./nginx/ssl/:/opt/ssl:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
      
  db:
    container_name: lemp_mariadb
    # image: mariadb:latest
    build: Dockerfile/mariadb/
    restart: unless-stopped
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=kali
      - MYSQL_DATABASE=surapong_db
      - MYSQL_USER=surapong
      - MYSQL_PASSWORD=kali

  # pma:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: lemp-phpmyadmin
  #   restart: always
  #   ports:
  #     - "8000:80"

  # database:
  #   image: mongo:4.4
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=kali
  #     - MONGO_INITDB_DATABASE=example
  #     - MONGO_INITDB_USERNAME=surapong
  #     - MONGO_INITDB_PASSWORD=kali
  #   volumes:
  #     - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
  #     - ./db:/data/db

networks:
  default:
    external:
      name:
        web_network